name: Build

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java: [15, 11, 8]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}

    - name: Pull Gradle Cache
      uses: actions/cache@v2
      id: gradle-cache
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-maven-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-java-${{ matrix.java }}

    - name: Setup Project
      run: |
         git config --global user.email "ci@github.com"
         git config --global user.name "Github CI"
         git config --global gc.auto 0
         sudo chmod -R -f 777 ./gradlew
         ./gradlew initGitSubmodules

    - name: Get MC Version
      run: echo "::set-output name=mcver::$(cat "Paper/work/BuildData/info.json"  | grep minecraftVersion | cut -d '"' -f 4)" 
      id: mcver

    - name: Pull Minecraft Decompile Cache
      uses: actions/cache@v2
      id: decompile-cache
      with:
        path: Paper/work/Minecraft/${{ steps.mcver.outputs.mcver }}
        key: ${{ hashFiles('Paper/work/BuildData/mappings/bukkit-$STEPS_MCVER_OUTPUTS_MCVER-cl.csrg') }}-${{ steps.mcver.outputs.mcver }}-${{ runner.os }}-java-${{ matrix.java }}-minecraft-decomp

    - name: Apply Patches
      run: |
        ./gradlew setupUpstream
        ./gradlew applyPatches

    - name: Pull Maven Cache
      uses: actions/cache@v2
      id: maven-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Build
      run: |
        ./gradlew clean build paperclip

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.java }}
        path: ${{ steps.mcver.outputs.mcver }}-paperclip.jar

    - name: Prepare Github Page Files
      run: |
        mkdir -p public
        cp ${{ steps.mcver.outputs.mcver }}-paperclip.jar public/
    - name: Deploy to Github Pages
      if: matrix.java == 8
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: releases/${{ steps.mcver.outputs.mcver }}


